---
abstract: 'Pattern-based Perl Recognizer'
author:
  - 'Damian Conway <DCONWAY@CPAN.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PPR
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  perl: '5.010'
version: '0.001000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
